### ISSUE TITLE
AWS Lambda

### ISSUE THREAD

**Issue by FredBesterwitch** [opentok/learning-opentok-node#7]
Guys trying to run this as a lambda does not work, any help would be appreciated

Nothing Happens, not getting any error..

`  opentok.createSession({ mediaMode: 'routed' }, function (err, session) {

            if (err) { 

              console.log(err);
              res.status(500).send({ error: 'createSession error:' + err });
              return;
            }
            // generate token
            token = opentok.generateToken(session.sessionId);
            res.setHeader('Content-Type', 'application/json');
            res.send({
              apiKey: apiKey,
              sessionId: session.sessionId,
              token: token
            });
          });`

**Comment by MichaelJolley** [comment]
Hi @FredBesterwitch, this issue is a little stale at this point. Are you still experiencing this issue?

**Comment by MichaelJolley** [comment]
I'm going to close this for now because it seems to be working now.  Feel free to comment if you experience this in the future.
