### ISSUE TITLE
ISSUE: Clicking on  http://localhost:8080/room/session 

### ISSUE THREAD

**Issue by DiptanshuMalviya** [opentok/learning-opentok-node#8]
**
{"error":"createSession error:Error: Failed to createSession. Error: The request failed: Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80"}
**
As following your instruction properply in Installation and Running on Local Host.
In the 4th step, I rename the file .envcopy to .env then entered API Key and Secret key from Tokbox Account.
After the 4th step, I entered npm start  then open local host:8080
it is  showing Error as below
{"error":"createSession error:Error: Failed to createSession. Error: The request failed: Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80"}

**Comment by MichaelJolley** [comment]
Hi @DiptanshuMalviya, sorry for the delay. Are you still experiencing this issue?

**Comment by MichaelJolley** [comment]
I'm going to close this for now because it seems to be working now.  Feel free to comment if you experience this in the future.
